name: local_query_filter
description: >
  A type-safe, composable query engine for client-side filtering, searching,
  sorting, and pagination of in-memory collections in Dart and Flutter.
version: 1.0.0
homepage: https://github.com/shifastudios/local_query_filter

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - filter
  - search
  - sort
  - pagination
  - query
